# Generated by Django 4.2.28 on 2026-03-03 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Sans titre', max_length=500)),
                ('content', models.JSONField(default=list)),
                ('owner_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mock Document',
                'verbose_name_plural': 'Mock Documents',
                'ordering': ['-updated_at'],
            },
        ),
    ]
